Krc/add GitHub actions
tighten/overload pull request #10
Opened 2020-12-16 15:09 UTC by krievley

Added the yml file to run the travis process on github actions.

2020-12-16 16:04 UTC, mattstauffer commented on .github/workflows/run-php-tests.yml
> +    branches: [ krc/add-github-actions ]
You'll want to update this to `main` before we merge

2020-12-16 16:05 UTC, mattstauffer requested changes

2020-12-16 16:05 UTC, mattstauffer commented on .github/workflows/run-php-tests.yml
> +      run: composer update ${{ matrix.composer_flag_string }} --no-interaction --prefer-source
It looks like this isn't actually running the tests?

2020-12-16 16:05 UTC, mattstauffer commented
Please delete any Travis files while you're at it, and add the GH Actions badge to the readme

2020-12-16 17:51 UTC, krievley commented
Matt, per your feedback I have tried adding better commit messages and performed the updates you requested:

1. Changed the branch to watch to "main".
2. Added a PHPUnit step to the config.
3. Removed the Travis CI file.
4. Added GitHub Actions Badge to the README

2020-12-17 04:18 UTC, mattstauffer commented
Thanks! One remaining note on commits: Please use the present imperative tense, so "Add" instead of "Added", "Create" instead of "Created", etc.

Additionally, you left the Travis badge still in the readme.

Please take the time to read each PR you make before submitting it so you can see if there's anything you could potentially catch before it makes it to the reviewer. Thanks!

2021-01-12 03:06 UTC, merged

2021-01-12 03:06 UTC, mattstauffer commented
Thanks @krievley!!